name: Query Snowflake using Azure AD OAuth

on:
  workflow_dispatch:

jobs:
  run-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install snowflake-connector-python requests

      - name: Upload token file (debug only)
        uses: actions/upload-artifact@v4
        with:
          name: token-debug
          path: token_debug.txt

      - name: Run query with OAuth token
        env:
          AZURE_TOKEN_ENDPOINT: ${{ secrets.AZURE_TOKEN_ENDPOINT }}
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          OAUTH_SCOPE: ${{ secrets.OAUTH_SCOPE }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: python query_snowflake.py
